name: Check and update Closure Compiler Nightly Build

on:
  schedule:
    - cron: "0 11,23 * * *"

jobs:
  update:
    name: Check and update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm i -g npm@latest
      - run: npm ci
      - run: npm test
      - run: ./github-update-nightly.sh
