name: Check and update Closure Compiler Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11,23 * * *"

jobs:
  update:
    name: Check and update
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
      - run: npm ci
      - run: npm test
      - run: ./github-update-nightly.sh
