name: Check and update Closure Compiler Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 11,23 * * *"

jobs:
  update:
    name: Check and update
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - run: npm ci
      - run: npm test
      - run: ./github-update-nightly.sh
